### ISSUE TITLE
Publish webappenhance in public Maven repository

### ISSUE THREAD

**Issue by michaldo** [pukkaone/webappenhance#2]
Do you plan to publish webappenhace as  public Maven artifact? It would be useful to simply join webappenhace to applications

**Comment by pukkaone** [comment]
The artifact is now available in the Maven Central repository.  The Maven coordinates are

```
<dependency>
  <groupId>com.github.pukkaone</groupId>
  <artifactId>webappenhance</artifactId>
  <version>1.0.1</version>
</dependency>
```
